### ISSUE TITLE
Half of the plugins not working anymore

### ISSUE THREAD

**Issue by nickbe** [dignajar/bludit#209]
half the plugins are not working anymore since version 1.0

Also I don't get why you renamed the folders?! 
I really don't get the sense in that?

**Comment by acrox999** [comment]
Plugins now require metadata.json to be listed. Either you create them yourself for the plugins that you want to use, or wait for the developers to update them.

They should work just fine with that file present regardless of the directory name changes.

**Comment by clickwork-git** [comment]
The renaming is because there was a problem when using names like "languages" or "plugins" for a post or page. The server cannot make a difference between the name of a directory or a permalink. Therefore names for the directory were choosed that hardly ever were used for a post or page.

This is not a problem of Bludit only, but all CMS or websites.

**Comment by nickbe** [comment]
Ok. Thanks.
I'll try creating the json files

**Comment by dignajar** [comment]
Fred made the updates this morning.. check now.

**Comment by nickbe** [comment]
Thanks. Most of them are working now. For the others I added the json file. So all is working again now.
Thanks

**Comment by nickbe** [comment]
Most of them are working again. For the others I created a json file.
Thanks!
