### ISSUE TITLE
Heading for the tag pages

### ISSUE THREAD

**Issue by mohanzeal** [dignajar/bludit#303]
I think it's good to have a heading for the tag pages. It's good for the seo.

if the url is https://blog.bludit.com/tag/Release . Instead of simply displaying the list of post related to release tag, why don't we have a Heading like Tag: Release in a h1 tag followed by the list of posts.

Thanks.

**Comment by Max-malRichtig** [comment]
This can be accomplished easily, but I'm afraid that this is a quite theme-specific request.

Either anyone can come up with a solid idea, how to implement this into bludit, so (almost) every theme handles it right, or we/you just have to edit every theme.

In order to give you an idea, how you can get the result you want:
```php
<?php
    if( ($Url->whereAmI()==='tag') ) {
        echo '<h1>The tag: '.$Url->slug().'</h1>';
    }
?>
```

Max

**Comment by acrox999** [comment]
True, this is very theme/template dependent. And I have not seen much of any templates that implement this.


Perhaps a plugin could be made to inject the heading onto the page so that it works universally but that will most definitely not look good on every theme.

**Comment by janxb** [comment]
This issue is theme dependent. Maybe there is a better place for your question? If you like to edit the theme by yourself, you are free to [fork the themes repository](https://github.com/dignajar/bludit-themes) and create a pull request :)

**Comment by mohanzeal** [comment]
I got it. Thanks Every one.
