### ISSUE TITLE
Fix include file in index.php theme

### ISSUE THREAD

**Issue by Fred89** [dignajar/bludit#34]
Replace all include('php
to include(dirname(__FILE__).'/php

**Comment by dignajar** [comment]
Hi Fred, why this changes ? doesn't work with the include without the dirname ?

**Comment by Fred89** [comment]
In some server i have this warning:
Warning: include(php/home.php) [function.include]: failed to open stream: No such file or directory in /home/u680092465/public_html/themes/pure/index.php on line 29

The direname directive, secure the include only in theme file.

**Comment by dignajar** [comment]
I read about this, yes is a problem in some servers, is good practice use the absolute path, I read the best way since PHP 5.3 is using __DIR__ instead dirname(__FILE__) and the slash use the variable DS, for Windows Servers.

include(__DIR__.DS.'php'.DS.'head.php')

is fucking ugly this include, more for the developers, I have a variable PATH_THEME with the absolute path.

include(PATH_THEME.'php'.DS.'head.php'), I think is the best and not so ugly, what do you think ?

**Comment by Fred89** [comment]
Ho i don't view your notification, i test this solution and i feedback ;)

**Comment by Fred89** [comment]
Ok work great with your change:
include(PATH_THEME_PHP. 'head.php')
